import type { Conversation } from '@/store';

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-001',
    customerName: 'Alice Johnson',
    customerIdentifier: '+1 555 010 0001',
    status: 'open',
    assignedTo: null,
    lastMessage: 'Is my order still on track for delivery today?',
    lastMessageAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    unreadCount: 2,
    messages: [
      {
        id: 'm-001-1',
        conversationId: 'conv-001',
        role: 'user',
        senderIdentifier: '+1 555 010 0001',
        content: 'Hi! I placed an order yesterday. Order #ORD-001.',
        timestamp: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-001-2',
        conversationId: 'conv-001',
        role: 'assistant',
        senderIdentifier: null,
        content: 'Hello Alice! Let me check that for you right away.',
        timestamp: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-001-3',
        conversationId: 'conv-001',
        role: 'assistant',
        senderIdentifier: null,
        content:
          'Your order is confirmed and has been dispatched. Estimated delivery is today between 2–5 PM.',
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-001-4',
        conversationId: 'conv-001',
        role: 'user',
        senderIdentifier: '+1 555 010 0001',
        content: 'Is my order still on track for delivery today?',
        timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'conv-002',
    customerName: 'Bob Martinez',
    customerIdentifier: '+1 555 010 0002',
    status: 'open',
    assignedTo: null,
    lastMessage: "Thanks! I'll wait for the refund.",
    lastMessageAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: 'm-002-1',
        conversationId: 'conv-002',
        role: 'user',
        senderIdentifier: '+1 555 010 0002',
        content: 'I want to return my item. It arrived damaged.',
        timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-002-2',
        conversationId: 'conv-002',
        role: 'assistant',
        senderIdentifier: null,
        content:
          "I'm sorry to hear that, Bob. I've raised a return request and a full refund will be processed within 3–5 business days.",
        timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-002-3',
        conversationId: 'conv-002',
        role: 'user',
        senderIdentifier: '+1 555 010 0002',
        content: "Thanks! I'll wait for the refund.",
        timestamp: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'conv-003',
    customerName: 'Carol White',
    customerIdentifier: '+1 555 010 0003',
    status: 'pending',
    assignedTo: null,
    lastMessage: 'Do you have this in size M?',
    lastMessageAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    unreadCount: 1,
    messages: [
      {
        id: 'm-003-1',
        conversationId: 'conv-003',
        role: 'user',
        senderIdentifier: '+1 555 010 0003',
        content: "Hey, I'm interested in the blue jacket from your latest collection.",
        timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-003-2',
        conversationId: 'conv-003',
        role: 'assistant',
        senderIdentifier: null,
        content:
          'Hi Carol! The blue jacket is available in sizes S, M, L, and XL. Which size are you looking for?',
        timestamp: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-003-3',
        conversationId: 'conv-003',
        role: 'user',
        senderIdentifier: '+1 555 010 0003',
        content: 'Do you have this in size M?',
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'conv-004',
    customerName: 'Dan Kim',
    customerIdentifier: '+1 555 010 0004',
    status: 'resolved',
    assignedTo: null,
    lastMessage: 'Great service, thank you!',
    lastMessageAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: 'm-004-1',
        conversationId: 'conv-004',
        role: 'user',
        senderIdentifier: '+1 555 010 0004',
        content: 'My payment failed but I was still charged. Can you help?',
        timestamp: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-004-2',
        conversationId: 'conv-004',
        role: 'assistant',
        senderIdentifier: null,
        content:
          "Hi Dan! I've looked into it — the charge was a pre-auth hold and will be released automatically within 24 hours.",
        timestamp: new Date(Date.now() - 25.5 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-004-3',
        conversationId: 'conv-004',
        role: 'user',
        senderIdentifier: '+1 555 010 0004',
        content: 'Great service, thank you!',
        timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'conv-005',
    customerName: 'Eva Chen',
    customerIdentifier: '+1 555 010 0005',
    status: 'open',
    assignedTo: null,
    lastMessage: 'Can I get a bulk discount for 10 units?',
    lastMessageAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    unreadCount: 3,
    messages: [
      {
        id: 'm-005-1',
        conversationId: 'conv-005',
        role: 'user',
        senderIdentifier: '+1 555 010 0005',
        content: "Hello! I'm representing a small business.",
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-005-2',
        conversationId: 'conv-005',
        role: 'user',
        senderIdentifier: '+1 555 010 0005',
        content: "We'd like to place a large order.",
        timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
      },
      {
        id: 'm-005-3',
        conversationId: 'conv-005',
        role: 'user',
        senderIdentifier: '+1 555 010 0005',
        content: 'Can I get a bulk discount for 10 units?',
        timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      },
    ],
  },
];
